tatoshis:
  # Tax rate in percent
  tax: 5.0
  # Tax sales or withdrawals?
  sales-tax: true
  # Whether or not the buyer will pay the sales tax (only used if 'sales-tax' is enabled)
  is-buyer-responsible: true
  # Username of the owner (All taxes go to this player)
  ownersUUID: 78e3a3ed-8528-4de5-a991-9ea087d7adfc
  # Value of single Bitcoin
  multiplier: 1000.0
  # Name of the in-game currency
  currency-name: 'Coin'
persistance:
#database properties
  url: [jdbc:mysql://localhost:3306/YourDataBaseNameHere]
  user: [your database user]
  password: [your database password]
tdcoin:
  # How much in-game currency is require to withdraw to Bitcoin.
  min-withdraw: 0
  # Transaction Confirmations required for crediting player?
  confirms: 1
  # Enable testnet blockchain
  testnet: true
self-check:
  # How often to do a total system check? (Hours or -1 to disable)
  delay: -1
  # Do a total system check on startup?
  startup: false
